// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yumigo.API.DbContext;

#nullable disable

namespace Yumigo.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Yumigo.API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Yumigo.API.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Appetizer",
                            Description = "Toasted bread with garlic butter and herbs",
                            Image = "garlic_bread.jpg",
                            Name = "Garlic Bread",
                            Price = 5.9900000000000002,
                            SpecialTag = "Vegetarian"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Appetizer",
                            Description = "Spicy buffalo wings with blue cheese dip",
                            Image = "chicken_wings.jpg",
                            Name = "Chicken Wings",
                            Price = 12.99,
                            SpecialTag = "Spicy"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Salad",
                            Description = "Crisp romaine with Caesar dressing and croutons",
                            Image = "caesar_salad.jpg",
                            Name = "Caesar Salad",
                            Price = 8.4900000000000002,
                            SpecialTag = "Vegetarian"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Main Course",
                            Description = "Classic pizza with tomato, mozzarella, and basil",
                            Image = "margherita_pizza.jpg",
                            Name = "Margherita Pizza",
                            Price = 14.99,
                            SpecialTag = "Vegetarian"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Main Course",
                            Description = "Fresh salmon with lemon herb sauce",
                            Image = "grilled_salmon.jpg",
                            Name = "Grilled Salmon",
                            Price = 22.989999999999998,
                            SpecialTag = "Gluten-Free"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Main Course",
                            Description = "Juicy beef patty with lettuce, tomato, and cheese",
                            Image = "beef_burger.jpg",
                            Name = "Beef Burger",
                            Price = 13.99,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 7,
                            Category = "Main Course",
                            Description = "Creamy risotto with wild mushrooms",
                            Image = "mushroom_risotto.jpg",
                            Name = "Mushroom Risotto",
                            Price = 16.489999999999998,
                            SpecialTag = "Vegetarian"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Side",
                            Description = "Crispy golden fries with ketchup",
                            Image = "french_fries.jpg",
                            Name = "French Fries",
                            Price = 4.9900000000000002,
                            SpecialTag = "Vegetarian"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Side",
                            Description = "Crispy battered onion rings",
                            Image = "onion_rings.jpg",
                            Name = "Onion Rings",
                            Price = 6.4900000000000002,
                            SpecialTag = "Vegetarian"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Dessert",
                            Description = "Warm chocolate cake with molten center",
                            Image = "lava_cake.jpg",
                            Name = "Chocolate Lava Cake",
                            Price = 7.9900000000000002,
                            SpecialTag = "Indulgent"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Dessert",
                            Description = "Creamy cheesecake with berry compote",
                            Image = "cheesecake.jpg",
                            Name = "Cheesecake",
                            Price = 8.9900000000000002,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 12,
                            Category = "Beverage",
                            Description = "Refreshing mint and lime cocktail",
                            Image = "mojito.jpg",
                            Name = "Mojito",
                            Price = 9.9900000000000002,
                            SpecialTag = "Alcoholic"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Beverage",
                            Description = "Chilled coffee with milk and sugar",
                            Image = "iced_coffee.jpg",
                            Name = "Iced Coffee",
                            Price = 4.4900000000000002,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 14,
                            Category = "Main Course",
                            Description = "Whole wheat wrap with fresh veggies and hummus",
                            Image = "veggie_wrap.jpg",
                            Name = "Veggie Wrap",
                            Price = 10.99,
                            SpecialTag = "Vegan"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Appetizer",
                            Description = "Chilled shrimp with tangy cocktail sauce",
                            Image = "shrimp_cocktail.jpg",
                            Name = "Shrimp Cocktail",
                            Price = 11.99,
                            SpecialTag = "Gluten-Free"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Main Course",
                            Description = "Fettuccine in creamy Alfredo sauce",
                            Image = "pasta_alfredo.jpg",
                            Name = "Pasta Alfredo",
                            Price = 15.49,
                            SpecialTag = "Vegetarian"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Salad",
                            Description = "Feta, olives, and cucumbers in olive oil dressing",
                            Image = "greek_salad.jpg",
                            Name = "Greek Salad",
                            Price = 9.4900000000000002,
                            SpecialTag = "Vegetarian"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Main Course",
                            Description = "Slow-cooked ribs with smoky BBQ sauce",
                            Image = "bbq_ribs.jpg",
                            Name = "BBQ Ribs",
                            Price = 24.989999999999998,
                            SpecialTag = "Spicy"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Beverage",
                            Description = "Freshly squeezed lemonade with mint",
                            Image = "lemonade.jpg",
                            Name = "Lemonade",
                            Price = 3.9900000000000002,
                            SpecialTag = "Non-Alcoholic"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Dessert",
                            Description = "Classic Italian dessert with coffee and mascarpone",
                            Image = "tiramisu.jpg",
                            Name = "Tiramisu",
                            Price = 8.4900000000000002,
                            SpecialTag = ""
                        });
                });

            modelBuilder.Entity("Yumigo.API.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderDetailId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Yumigo.API.Models.OrderHeader", b =>
                {
                    b.Property<int>("OrderHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderHeaderId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("PickUpEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickUpName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickUpPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalItem")
                        .HasColumnType("integer");

                    b.HasKey("OrderHeaderId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Yumigo.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Yumigo.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yumigo.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Yumigo.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yumigo.API.Models.OrderDetail", b =>
                {
                    b.HasOne("Yumigo.API.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yumigo.API.Models.OrderHeader", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Yumigo.API.Models.OrderHeader", b =>
                {
                    b.HasOne("Yumigo.API.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Yumigo.API.Models.OrderHeader", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
